version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mqtt_config:/mosquitto/config
      - mqtt_data:/mosquitto/data
      - mqtt_logs:/mosquitto/log

  database:
    image: mariadb
    environment:
      MARIADB_DATABASE: climate
      MARIADB_USER: cooluser
      MARIADB_PASSWORD: changeme
      MARIADB_ROOT_PASSWORD: reallychangeme
    volumes:
      - db:/var/lib/mysql

  db_admin:
    image: phpmyadmin
    ports:
      - 8089:80
    environment:
      PMA_HOST: database

  nginx:
    image: nginx:alpine
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  web:
    build:
      context: .
      dockerfile: frontend.Dockerfile

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      - DB_USER=cooluser
      - DB_PASS=changeme
      - DB_NAME=climate
      - DB_HOST=database

  listen:
    build:
      context: .
      dockerfile: listen.Dockerfile
    environment:
      - DB_USER=cooluser
      - DB_PASS=changeme
      - DB_NAME=climate
      - DB_HOST=database
      - AZURE_CONNECTION=
      - AZURE_ENABLE=0
      - MQTT_USER=
      - MQTT_PASS=
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
      - MQTT_TOPIC=climate

  cron:
    build:
      context: .
      dockerfile: cron.Dockerfile
    environment:
      - DB_USER=cooluser
      - DB_PASS=changeme
      - DB_NAME=climate
      - DB_HOST=database
      - AZURE_CONNECTION=

volumes:
  db:
  mqtt_logs:
  mqtt_data:
