version: '3.8'

services:
  database:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_ROOT_PASSWORD: ${DB_PASS}

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8089:80
    environment:
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
      PMA_HOST: database
