version: '3.9'

services:
  listing:
    build:
      context: .
      dockerfile: listen.Dockerfile
    environment:
      - DB_USER
      - DB_PASS
      - DB_NAME
      - DB_HOST
      - MQTT_USER
      - MQTT_PASS
      - MQTT_HOST
      - MQTT_PORT
      - MQTT_TOPIC
      - AZURE_CONNECTION
      - AZURE_ENABLE
    depends_on:
      - database

  cron:
    build:
      context: .
      dockerfile: cron.Dockerfile
    environment:
      - DB_USER
      - DB_PASS
      - DB_NAME
      - DB_HOST
      - AZURE_CONNECTION
    depends_on:
      - database

  database:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8089:80
    environment:
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
      PMA_HOST: database
